name: glade_forms_workspace

packages:
  - glade_forms
  - glade_forms/example
  - storybook

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  setup:
    description: Completely setups project
    run: |
      melos exec -- fvm flutter pub get
      melos run gallery_setup

  setup:win:
    description: Completely setups project
    run: |
      melos exec -- fvm flutter pub get ^
      melos run gallery_setup:win

  # ANALYZING

  lint:all:
    run: melos run lint:dart && melos run lint:dcm
    description: Run all static analysis checks.

  lint:dart:
    run: melos exec -c 10 -- dart analyze --fatal-infos
    description: Run Dart static analysis checks.

  lint:dcm:
    run: melos exec -c 10 -- dcm analyze . --fatal-style --fatal-performance --fatal-warnings
    description: Run DCM static analysis checks.

  # TESTING

  test:
    run: melos exec -- flutter test
    packageFilters:
      dirExists: test
    description: Run all Dart tests.

  # Gallery
  gallery_setup:
    run: |
      melos exec -- flutter pub run easy_localization:generate -S "assets/translations" -o locale_loader.g.dart
      melos exec -- fvm flutter pub run easy_localization:generate -S "assets/translations" --skip-unnecessary-keys -f keys -o locale_keys.g.dart
    packageFilters:
      dependsOn: easy_localization

  gallery_setup:win:
    run: |
      melos exec -- flutter pub run easy_localization:generate -S "assets/translations" -o locale_loader.g.dart ^
      melos exec -- fvm flutter pub run easy_localization:generate -S "assets/translations" --skip-unnecessary-keys -f keys -o locale_keys.g.dart
    packageFilters:
      dependsOn: easy_localization
