include: package:netglade_analysis/lints.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/"

linter:
  rules:
    avoid_redundant_argument_values: false

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  rules:
    - avoid-passing-default-values
