include: package:netglade_analysis/lints.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/"

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  rules:
    - prefer-correct-callback-field-name: false
