import 'package:glade_forms_devtools_extension/src/models/child_glade_model_description.dart';
import 'package:glade_forms_devtools_extension/src/models/glade_input_description.dart';
import 'package:glade_forms_devtools_extension/src/models/glade_model_description.dart';

/// Mock data scenarios for debugging the extension UI.
// ignore: prefer-match-file-name, keep in same file
enum MockScenario {
  composedModel,
  multipleModels,
  noModels,
  singleModel,
}

abstract final class MockDataProvider {
  static List<GladeModelDescription> getModelsForScenario(MockScenario scenario) {
    return switch (scenario) {
      .noModels => [],
      .singleModel => [_createSingleModel()],
      .composedModel => [_createComposedModel()],
      .multipleModels => [
        _createSingleModel(id: 'model-1', type: 'LoginForm'),
        _createSingleModel(
          id: 'model-2',
          type: 'RegistrationForm',
          isDirty: true,
          isValid: false,
        ),
        _createComposedModel(),
      ],
    };
  }

  static GladeModelDescription _createSingleModel({
    String? id,
    String? type,
    bool isValid = true,
    bool isDirty = false,
  }) {
    return GladeModelDescription(
      id: id ?? 'single-model-1',
      type: type ?? 'UserProfileForm',
      debugKey: type ?? 'UserProfileForm',
      isValid: isValid,
      isPure: !isDirty,
      isDirty: isDirty,
      isUnchanged: !isDirty,
      inputs: [
        GladeInputDescription(
          key: 'email',
          type: 'GladeInput<String>',
          strValue: 'user@example.com',
          value: 'user@example.com',
          initialValue: 'user@example.com',
          isValid: true,
          isPure: !isDirty,
          isUnchanged: !isDirty,
          hasConversionError: false,
          errors: const [],
          warnings: const [],
        ),
        GladeInputDescription(
          key: 'username',
          type: 'GladeInput<String>',
          strValue: 'john_doe',
          value: 'john_doe',
          initialValue: 'john_doe',
          isValid: true,
          isPure: !isDirty,
          isUnchanged: !isDirty,
          hasConversionError: false,
          errors: const [],
          warnings: const [],
        ),
        GladeInputDescription(
          key: 'age',
          type: 'GladeInput<int>',
          strValue: '25',
          value: 25,
          initialValue: 25,
          isValid: isValid,
          isPure: !isDirty,
          isUnchanged: !isDirty,
          hasConversionError: false,
          errors: isValid ? [] : ['Age must be between 18 and 100'],
          warnings: const [],
        ),
        const GladeInputDescription(
          key: 'newsletter',
          type: 'GladeInput<bool>',
          strValue: 'true',
          value: true,
          initialValue: false,
          isValid: true,
          isPure: false,
          isUnchanged: false,
          hasConversionError: false,
          errors: [],
          warnings: [],
        ),
      ],
      formattedErrors: isValid ? '' : 'Age must be between 18 and 100',
    );
  }

  static GladeModelDescription _createComposedModel() {
    return const GladeModelDescription(
      id: 'composed-model-1',
      type: 'OrderCheckoutForm',
      debugKey: 'OrderCheckoutForm',
      isValid: false,
      isPure: false,
      isDirty: true,
      isUnchanged: false,
      inputs: [
        GladeInputDescription(
          key: 'orderNumber',
          type: 'GladeInput<String>',
          value: 'ORD-12345',
          strValue: 'ORD-12345',
          initialValue: 'ORD-12345',
          isValid: true,
          isPure: true,
          isUnchanged: true,
          hasConversionError: false,
          errors: [],
          warnings: [],
        ),
        GladeInputDescription(
          key: 'totalAmount',
          type: 'GladeInput<double>',
          strValue: '299.99',
          value: 299.99,
          initialValue: 299.99,
          isValid: true,
          isPure: true,
          isUnchanged: true,
          hasConversionError: false,
          errors: [],
          warnings: [],
        ),
      ],
      formattedErrors: 'Shipping address is required',
      isComposed: true,
      childModels: [
        ChildGladeModelDescription(
          id: 'child-1',
          index: 0,
          type: 'BillingAddressForm',
          debugKey: 'BillingAddressForm',
          isValid: true,
          isPure: false,
          isDirty: true,
          isUnchanged: false,
          inputs: [
            GladeInputDescription(
              key: 'street',
              type: 'GladeInput<String>',
              strValue: '123 Main St',
              value: '123 Main St',
              initialValue: '123 Main St',
              isValid: true,
              isPure: true,
              isUnchanged: true,
              hasConversionError: false,
              errors: [],
              warnings: [],
            ),
            GladeInputDescription(
              key: 'city',
              type: 'GladeInput<String>',
              value: 'New York',
              strValue: 'New York',
              initialValue: 'Boston',
              isValid: true,
              isPure: false,
              isUnchanged: false,
              hasConversionError: false,
              errors: [],
              warnings: [],
            ),
            GladeInputDescription(
              key: 'zipCode',
              type: 'GladeInput<String>',
              strValue: '10001',
              value: '10001',
              initialValue: '10001',
              isValid: true,
              isPure: true,
              isUnchanged: true,
              hasConversionError: false,
              errors: [],
              warnings: [],
            ),
          ],
          formattedErrors: '',
        ),
        ChildGladeModelDescription(
          id: 'child-2',
          index: 1,
          type: 'ShippingAddressForm',
          debugKey: 'ShippingAddressForm',
          isValid: false,
          isPure: false,
          isDirty: true,
          isUnchanged: false,
          inputs: [
            GladeInputDescription(
              key: 'street',
              type: 'GladeInput<String>',
              strValue: '',
              value: null,
              isValid: false,
              isPure: true,
              isUnchanged: true,
              hasConversionError: false,
              errors: ['Street is required'],
              warnings: [],
            ),
            GladeInputDescription(
              key: 'street-empty',
              type: 'GladeInput<String>',
              strValue: '',
              value: '',
              initialValue: '',
              isValid: false,
              isPure: true,
              isUnchanged: true,
              hasConversionError: false,
              errors: ['Street is required'],
              warnings: [],
            ),
            GladeInputDescription(
              key: 'city',
              type: 'GladeInput<String>',
              strValue: 'San Francisco',
              value: 'San Francisco',
              initialValue: 'San Francisco',
              isValid: true,
              isPure: true,
              isUnchanged: true,
              hasConversionError: false,
              errors: [],
              warnings: [],
            ),
            GladeInputDescription(
              key: 'zipCode',
              type: 'GladeInput<String>',
              strValue: '94102',
              value: 94102,
              initialValue: 94102,
              isValid: true,
              isPure: true,
              isUnchanged: true,
              hasConversionError: false,
              errors: [],
              warnings: [],
            ),
          ],
          formattedErrors: 'Street is required',
        ),
        ChildGladeModelDescription(
          id: 'child-3',
          index: 2,
          type: 'PaymentMethodForm',
          debugKey: 'PaymentMethodForm',
          isValid: true,
          isPure: true,
          isDirty: false,
          isUnchanged: true,
          inputs: [
            GladeInputDescription(
              key: 'cardNumber',
              type: 'GladeInput<String>',
              strValue: '**** **** **** 1234',
              value: '**** **** **** 1234',
              initialValue: '**** **** **** 1234',
              isValid: true,
              isPure: true,
              isUnchanged: true,
              hasConversionError: false,
              errors: [],
              warnings: [],
            ),
            GladeInputDescription(
              key: 'expiryDate',
              type: 'GladeInput<String>',
              strValue: '12/25',
              value: '12/25',
              initialValue: '12/25',
              isValid: true,
              isPure: true,
              isUnchanged: true,
              hasConversionError: false,
              errors: [],
              warnings: [],
            ),
            GladeInputDescription(
              key: 'cvv',
              type: 'GladeInput<String>',
              strValue: '***',
              value: '***',
              initialValue: '***',
              isValid: true,
              isPure: true,
              isUnchanged: true,
              hasConversionError: false,
              errors: [],
              warnings: [],
            ),
          ],
          formattedErrors: '',
        ),
      ],
    );
  }
}
