name: glade_forms_example
description: Glade Forms - Interactive example
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_highlighter: ^0.1.1
  flutter_hooks: ^0.20.1
  flutter_markdown: ^0.6.17+3
  glade_forms:
    path: ../../glade_forms
  provider: ^6.0.2
  widgetbook: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  netglade_analysis: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - lib/usecases/
