name: ci

on:
  pull_request:

jobs:
  glade_forms:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure FVM
        uses: kuhnroyal/flutter-fvm-config-action@v3
        id: fvm-config-action

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      # - name: Install DCM
      #   uses: CQLabs/setup-dcm@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     version: 1.26.2

      - uses: bluefireteam/melos-action@v3

      # - name: Dart Analyze
      #   run: melos run lint:dart

      # - name: Run DCM
      #   uses: CQLabs/dcm-action@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     ci-key: ${{ secrets.DCM_KEY }}
      #     email: ${{ secrets.DCM_EMAIL }}
      #     folders: .
      #     fatal-found: true

      - name: Test
        run: melos run test
