name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  glade_forms:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure FVM
        uses: kuhnroyal/flutter-fvm-config-action@v1
        with:
          path: ".fvm/fvm_config.json"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install DCM
        uses: CQLabs/setup-dcm@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: bluefireteam/melos-action@v2

      - name: Dart Analyze
        run: melos run lint:dart

      - name: Run DCM
        uses: CQLabs/dcm-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ci_key: ${{ secrets.DCM_KEY }}
          email: ${{ secrets.DCM_EMAIL }}
          folders: .
          fatal_style: true
          fatal_performance: true
          fatal_warnings: true

      - name: Test
        run: melos run test
