name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./storybook

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure FVM
        uses: kuhnroyal/flutter-fvm-config-action@v1
        with:
          path: ".fvm/fvm_config.json"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - uses: bluefireteam/melos-action@v2

      - name: Setup
        run: |
          flutter pub run easy_localization:generate -S "assets/translations" -o locale_loader.g.dart
          flutter pub run easy_localization:generate -S "assets/translations" --skip-unnecessary-keys -f keys -o locale_keys.g.dart

      - name: Build Storybook for Web
        run: flutter build web --base-href "/glade_forms/"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: "storybook/build/web/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
